
package com.stucomm.mock.osiris;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResultaatService", targetNamespace = "http://osiris/services/ResultaatService.wsdl", wsdlLocation = "file:/Users/dickdijk/StuComm/mockosiris/src/main/resources/osiris.wsdl")
public class ResultaatService_Service
    extends Service
{

    private final static URL RESULTAATSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESULTAATSERVICE_EXCEPTION;
    private final static QName RESULTAATSERVICE_QNAME = new QName("http://osiris/services/ResultaatService.wsdl", "ResultaatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/dickdijk/StuComm/mockosiris/src/main/resources/osiris.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESULTAATSERVICE_WSDL_LOCATION = url;
        RESULTAATSERVICE_EXCEPTION = e;
    }

    public ResultaatService_Service() {
        super(__getWsdlLocation(), RESULTAATSERVICE_QNAME);
    }

    public ResultaatService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESULTAATSERVICE_QNAME, features);
    }

    public ResultaatService_Service(URL wsdlLocation) {
        super(wsdlLocation, RESULTAATSERVICE_QNAME);
    }

    public ResultaatService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESULTAATSERVICE_QNAME, features);
    }

    public ResultaatService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResultaatService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResultaatService
     */
    @WebEndpoint(name = "ResultaatServicePort")
    public ResultaatService getResultaatServicePort() {
        return super.getPort(new QName("http://osiris/services/ResultaatService.wsdl", "ResultaatServicePort"), ResultaatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResultaatService
     */
    @WebEndpoint(name = "ResultaatServicePort")
    public ResultaatService getResultaatServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://osiris/services/ResultaatService.wsdl", "ResultaatServicePort"), ResultaatService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESULTAATSERVICE_EXCEPTION!= null) {
            throw RESULTAATSERVICE_EXCEPTION;
        }
        return RESULTAATSERVICE_WSDL_LOCATION;
    }

}
