
package com.stucomm.mock.osiris;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResultaatService", targetNamespace = "http://osiris/services/ResultaatService.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResultaatService {


    /**
     * 
     * @param pTaal
     * @param pStudentnummer
     * @return
     *     returns com.com.stucomm.mock.osiris.OswPorResultatenRtUserArray
     */
    @WebMethod(action = "http://osiris/services/ResultaatService.wsdl/resultaten")
    @WebResult(name = "result", partName = "result")
    public OswPorResultatenRtUserArray resultaten(
            @WebParam(name = "pStudentnummer", partName = "pStudentnummer")
                    String pStudentnummer,
            @WebParam(name = "pTaal", partName = "pTaal")
                    String pTaal);

    /**
     * 
     * @param pCursus
     * @param pTaal
     * @param pStudentnummer
     * @param pCollegejaar
     * @return
     *     returns com.com.stucomm.mock.osiris.OswPorResultatenRtUserArray
     */
    @WebMethod(action = "http://osiris/services/ResultaatService.wsdl/resultatenCursus")
    @WebResult(name = "result", partName = "result")
    public OswPorResultatenRtUserArray resultatenCursus(
            @WebParam(name = "pStudentnummer", partName = "pStudentnummer")
                    String pStudentnummer,
            @WebParam(name = "pCursus", partName = "pCursus")
                    String pCursus,
            @WebParam(name = "pCollegejaar", partName = "pCollegejaar")
                    BigDecimal pCollegejaar,
            @WebParam(name = "pTaal", partName = "pTaal")
                    String pTaal);

}
